name: 'Pandiff Prose Changes'
description: 'Runs pandiff on files changed in a PR'
author: 'carafelix'
inputs:
  repo-token:
    description: 'GitHub token for API access'
    required: true
outputs:
  diffs:
    description: 'Concatenated diffs for changed files'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run Pandiff Prose Changes
      run: node src/index.js
      shell: bash
      env:
        INPUT_REPO-TOKEN: ${{ inputs.repo-token }}
