name: 'Pandiff Prose Changes'
description: 'Runs pandiff on files changed in a PR'
author: 'carafelix'
inputs:
   file_extensions:
    description: 'File extensions to diff separated by a space like: "*.md *.html *.etc"'
    required: false
    default: '*.md'
outputs:
  diffs:
    description: 'Concatenated diffs for changed files'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: Install pandoc
      run: sudo apt install -y pandoc
      shell: bash

    - name: Install dependencies
      run: npm i -g pandiff
      shell: bash

    
    - name: setup git pandiff
      run: |
        git config --global difftool.pandiff.cmd 'pandiff $LOCAL $REMOTE -t html'
      shell: bash

    - name: Run pandiff difftool on prose files
      run: |
        echo "File extensions: ${{ inputs.file_extensions }}"
        IFS=' ' read -ra EXTENSIONS <<< "${{ inputs.file_extensions }}"

        for file in $(git diff --name-only ${{ github.event.pull_request.base.ref }}..HEAD -- '${EXTENSIONS[@]}'); do
          echo "Diffing $file"

          diff_result=$(git difftool -t pandiff -y ${{ github.event.pull_request.base.ref }}..HEAD -- "$file" || true)
          diffs_output="${diffs_output}\n\nfilename: ${file}\n${diff_result}\n"
        done
        echo -e "diffs<<EOF\n${diffs_output}\nEOF" >> $GITHUB_OUTPUT
      shell: bash
      id: diffs
