name: 'Pandiff Prose Changes'
description: 'Runs pandiff on files changed in a PR'
author: 'carafelix'

outputs:
  diffs:
    description: 'Concatenated diffs for changed files'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: Install dependencies
      run: npm i -g pandiff
      shell: bash

    - name: setup git pandiff
      run: |
        git config --global difftool.pandiff.cmd 'pandiff ${{ github.event.pull_request.base.ref }} $HEAD -t html'
        git config --global alias.pandiff 'difftool -t pandiff -y'
      shell: bash

    - name: Run pandiff with input
      run: echo "diffs=$(git pandiff)" >> $GITHUB_OUTPUT
      id: diffs
      shell: bash
