name: 'Pandiff Prose Changes'
description: 'Runs pandiff on files changed in a PR'
author: 'carafelix'

inputs:
  file1:
    description: 'file1'
  file2:
    description: 'file2'

outputs:
  diffs:
    description: 'Concatenated diffs for changed files'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm i -g pandiff
      shell: bash

    - name: setup git pandiff
      run: |
        git config --global difftool.pandiff.cmd 'pandiff "$LOCAL" "$REMOTE" -t html'
        git config --global alias.pandiff 'difftool -t pandiff -y'

    - name: Run pandiff with input
      run: git diff
      shell: bash
