name: 'Pandiff Prose Changes'
description: 'Runs pandiff on files changed in a PR'
author: 'carafelix'
inputs:
   file_extensions:
    description: 'File extensions to diff ["*.md","*.html"]'
    required: false
    default: '*.md'
outputs:
  diffs:
    description: 'Concatenated diffs for changed files'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: Install pandoc
      run: sudo apt install -y pandoc
      shell: bash

    - name: Install dependencies
      run: npm i -g pandiff
      shell: bash

    - name: Run pandiff difftool on prose files
      run: |
        for file in $(git diff --name-only ${{ github.event.pull_request.base.ref }}..HEAD -- '*.md' '*.txt'); do
          echo "Diffing $file"
          git difftool -t pandiff ${{ github.event.pull_request.base.ref }}..HEAD -- "$file"
        done
      shell: bash
